voronoi1: voronoi1.o tower.o dcel.o
	gcc -Wall -g -o voronoi1 voronoi1.o tower.o dcel.o

voronoi1.o: voronoi1.c
	gcc -Wall -g -c voronoi1.c

tower.o: tower.h tower.c
	gcc -Wall -g -c tower.c

dcel.o: dcel.h dcel.c
	gcc -Wall -g -c dcel.c

